[build]
  command = "make build && hugo -s site -d ../dist"
  functions = "functions"
  publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.40.3"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/pubu/smile-feedback"
