[build]
  command = "make build && hugo -s site -d ../dist"
  functions = "functions"
  publish = "dist"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/pubu/test-hugo"
